---
title: "Handling the habitatmap"
date: '`r paste("Version",lubridate::now())`'
output:
  html_document:
    number_sections: yes
    code_folding: show
    includes:
      in_header: ../header.html
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
---

```{r setup, message=FALSE, echo=FALSE}
options(stringsAsFactors = FALSE)
library(sf)
library(dplyr)
library(n2khab)
library(knitr)
opts_chunk$set(
  echo = TRUE,
  dpi = 300
)
```


# A few checks of the habitatmap_stdized data source

```{r}
filepath <- file.path(fileman_up("n2khab_data"),
                      "20_processed/habitatmap_stdized/habitatmap_stdized.gpkg")
habitatmap_polygons <- st_read(filepath, layer = "habitatmap_polygons")
habitatmap_types <- st_read(filepath, layer = "habitatmap_types")
```


Do all polygons from the sf object have a unique ID?

```{r}
habitatmap_polygons %>% 
  st_drop_geometry %>% 
  count(polygon_id) %>% 
  filter(n > 1) %>% 
  nrow == 0
```

Is the number of unique IDs in the dataframe the same as the number of polygons in the sf object?

```{r}
habitatmap_types %>% 
  distinct(polygon_id) %>% 
  nrow == nrow(habitatmap_polygons)
```

Do all polygon IDs from the dataframe coincide with those of the sf object?

```{r message=FALSE}
habitatmap_types %>% 
  inner_join(habitatmap_polygons) %>% 
  nrow == nrow(habitatmap_types)
```

Number of polygons with phab = 0:

```{r}
habitatmap_types %>% 
  filter(phab == 0) %>% 
  nrow()
```

